---
# tasks file for common
- name: install common packages
  become: yes
  yum:
    name:
      - httpd
      - js
    state: present
  
- name: Start and enable apache
  become: yes
  service:
    name: httpd
    state: started
    enabled: yes

- name: Copy source code 
  become: yes
  synchronize:
    src: "{{playbook_dir}}/../../"
    dest: "/opt/todo-app"
    recursive: yes
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=.github"
      - "--exclude=ansible"