---
- name: Provision and configure ec2 server
  hosts: localhost
  gather_facts: no 

  roles:
    - ec2_launch

- name: Configuration of Ec2 instances
  hosts: launched_ec2_instances
  gather_facts: yes
  roles:
    - common